# Generated by Django 6.0.6 on 2026-07-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_shelter_animal_shelter'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='contact_whatsapp',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
